export type ChangeType = 'positive' | 'negative';
export type Variant = 'pink' | 'yellow' | 'green' | 'blue' | 'purple' | 'orange' | 'red';
export interface StatCardType {
  title: string;
  value: string;
  change: string;
  changeType: ChangeType;
  icon: any;
  variant: Variant;
}


//  Merchant 
export interface Merchant {
  id: number;
  name: string;
  brandImage: string;
  ownerName: string;
  profile: string;
  phone: string;
  email: string;
  totalProducts: number;
  totalOrders: number;
  totalRevenue: number;
  commissionPaid: number;
  joinDate: string;
  status: 'active' | 'inactive' | 'suspended' | 'pending';
  rating: number;
}


//  Product Category
export interface ProductCategoryType {
  id: number;
  name: string;
  totalProducts: number;
  totalMerchants: number;
  totalRevenue: number;
  status: 'active' | 'inactive';
}


export interface CustomerStats {
  name: string;
  totalSpent: number;   // Total amount spent
  orders: number;       // Number of orders
  lastOrderDate: string; // ISO date string
}

export interface VendorStats {
  name: string;
  totalRevenue: number; // Revenue generated by this vendor
  products: number;     // Number of products
  lastActive: string;   // ISO date string
}

export interface Transaction {
  id: string;
  customerName: string;
  amount: number;
  date: string;
  status: 'completed' | 'pending' | 'failed';
  type: 'payment' | 'refund' | 'payout';
}

export interface FeedbackType {
  id: string;
  customerName: string;
  customerAvatar?: string;
  rating: number;
  comment: string;
  date: string;
  appVersion?: string;
  deviceInfo?: string;
  category: 'marketplace' | 'app';
  status: 'pending' | 'resolved' | 'hidden';
  productName?: string;
  merchantName?: string;
}


export interface AccountDashboard {
  fullname: string;
  role: string;
  profile_url?: string;
}